import os

SYMBOLS = [
    "BTCUSDT", "ETHUSDT", "BNBUSDT", "SOLUSDT", "XRPUSDT",
    "ADAUSDT", "DOGEUSDT", "TRXUSDT", "AVAXUSDT", "LINKUSDT",
    "DOTUSDT", "NEARUSDT", "UNIUSDT", "LTCUSDT", "BCHUSDT",
    "ETCUSDT", "XLMUSDT", "ATOMUSDT", "ICPUSDT", "APTUSDT",
    "FILUSDT", "ARBUSDT", "OPUSDT", "INJUSDT", "SUIUSDT",
    "SEIUSDT", "TIAUSDT", "PYTHUSDT", "WLDUSDT", "STRKUSDT",
    "DYDXUSDT", "SANDUSDT", "MANAUSDT", "AXSUSDT", "GALAUSDT",
    "CHZUSDT", "ENJUSDT", "THETAUSDT", "FETUSDT", "RNDRUSDT",
    "TAOUSDT", "GRTUSDT", "AAVEUSDT", "PENDLEUSDT", "COMPUSDT",
    "YFIUSDT", "SNXUSDT", "CRVUSDT", "RUNEUSDT", "SUSHIUSDT",
    "1INCHUSDT", "LDOUSDT", "STXUSDT", "IMXUSDT", "FLOWUSDT",
    "ROSEUSDT", "IOTAUSDT", "VETUSDT", "NEOUSDT", "QTUMUSDT",
    "ZILUSDT", "KNCUSDT", "BATUSDT", "ONTUSDT", "BANDUSDT",
    "RLCUSDT", "BELUSDT", "SKLUSDT", "COTIUSDT", "CHRUSDT",
    "ALICEUSDT", "HBARUSDT", "ONEUSDT", "CELRUSDT", "HOTUSDT",
    "MTLUSDT", "OGNUSDT", "GTCUSDT", "IOTXUSDT", "MASKUSDT",
    "ATAUSDT", "C98USDT", "ARUSDT", "CTSIUSDT", "LPTUSDT",
    "ENSUSDT", "PEOPLEUSDT", "DUSKUSDT", "API3USDT", "GMTUSDT",
    "APEUSDT", "WOOUSDT", "JASMYUSDT", "STGUSDT", "SPELLUSDT",
    "JUPUSDT", "ACHUSDT", "SSVUSDT", "LQTYUSDT", "IDUSDT",
]

TIMEFRAMES = ["15m", "1h", "4h"]

# Indicators
VOL_MA_LEN   = 20
TREND_EMA_LEN = 50
ATR_LEN       = 14

# Strength weights (same as Pine Script)
GAP_WEIGHT    = 40
VOL_WEIGHT    = 30
TREND_WEIGHT  = 20
CANDLE_WEIGHT = 10

# Alert thresholds
MIN_STRENGTH_TO_ALERT = 70  # only strong FVGs (>=70)

# Regime bands (deviation from EMA)
DOM_NEUTRAL_BAND = 0.0015   # 0.15%
BTC_NEUTRAL_BAND = 0.0020   # 0.20%

# Confirmation filters
VOL_SPIKE_MED = 1.5
VOL_SPIKE_HIGH = 2.0
DISPLACEMENT_BODY_PCT = 65.0
MIN_CONFIRM_SCORE_ALERT = 35

# Invalidation
INVALID_ATR_BUFFER = 0.15
INVALID_LOOKAHEAD_BARS = 6

# Polling
POLL_INTERVAL_SEC = 30
KLINES_LIMIT = 100

# Telegram
BOT_TOKEN = os.environ["TELEGRAM_BOT_TOKEN"]
CHAT_ID   = os.environ["TELEGRAM_CHAT_ID"]

# Binance
BASE_URL = "https://fapi.binance.com"
