ALTER TABLE user_trades ADD COLUMN IF NOT EXISTS tp1_order_id TEXT;
ALTER TABLE user_trades ADD COLUMN IF NOT EXISTS tp1_qty DOUBLE PRECISION;
ALTER TABLE user_trades ADD COLUMN IF NOT EXISTS tp2_qty DOUBLE PRECISION;
