services:
  trade_executor:
    image: ghcr.io/${GH_OWNER}/trade_executor:latest
    restart: unless-stopped
    environment:
      DATABASE_URL: ${DATABASE_URL}
      MASTER_ENCRYPTION_KEY: ${MASTER_ENCRYPTION_KEY}
      BINANCE_PROXY_URL: ${BINANCE_PROXY_URL}
      INTERNAL_TOKEN: ${INTERNAL_TOKEN}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
    expose: ["8014"]
    networks:
      - default
      - fvg-net

  telegram_bot:
    image: ghcr.io/${GH_OWNER}/telegram_bot:latest
    restart: unless-stopped
    environment:
      DATABASE_URL: ${DATABASE_URL}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
    networks:
      - default
      - fvg-net

  dashboard:
    image: ghcr.io/${GH_OWNER}/dashboard:latest
    restart: unless-stopped
    environment:
      DATABASE_URL: ${DATABASE_URL}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      INTERNAL_TOKEN: ${INTERNAL_TOKEN}
      EXECUTOR_URL: http://trade_executor:8014
      NEXT_PUBLIC_BOT_USERNAME: ${BOT_USERNAME}
      HOSTNAME: 0.0.0.0
    expose: ["3000"]
    networks:
      - default
      - fvg-net
      - coolify
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.gzip.compress=true"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.http-fvglive.entryPoints=http"
      - "traefik.http.routers.http-fvglive.middlewares=redirect-to-https"
      - "traefik.http.routers.http-fvglive.rule=Host(`fvg-live.uponlytrader.xyz`) && PathPrefix(`/`)"
      - "traefik.http.routers.http-fvglive.service=http-fvglive"
      - "traefik.http.routers.https-fvglive.entryPoints=https"
      - "traefik.http.routers.https-fvglive.middlewares=gzip"
      - "traefik.http.routers.https-fvglive.rule=Host(`fvg-live.uponlytrader.xyz`) && PathPrefix(`/`)"
      - "traefik.http.routers.https-fvglive.service=https-fvglive"
      - "traefik.http.routers.https-fvglive.tls=true"
      - "traefik.http.routers.https-fvglive.tls.certresolver=letsencrypt"
      - "traefik.http.services.http-fvglive.loadbalancer.server.port=3000"
      - "traefik.http.services.https-fvglive.loadbalancer.server.port=3000"

networks:
  default:
  fvg-net:
    external: true
    name: n1hxl7f2x39ecqjths0u6446
  coolify:
    external: true
